[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
    "npm ci",
    "pip3 install -r scripts/requirements.txt"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "npm run start"